"""Build, verify, activate, and retain complete Project Board host releases.

This module deliberately uses only the Python standard library. The source
installer loads it before any Project Board dependency is installed, while an
already-running ``pb source`` command imports the same functions normally.
"""

from __future__ import annotations

import hashlib
import json
import os
import shlex
import shutil
import subprocess
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence


INSTALLATION_SCHEMA = "project-board.client-release-installation.v1"
INSTALLATION_MARKER = "installation.json"
RELEASES_DIR = "releases"
CURRENT_LINK = "current"
VENV_DIR = "venv"
LAUNCHER_VERSION = 2
LAUNCHER_MARKER = "Generated by Project Board release installer."
LEGACY_LAUNCHER_MARKERS = (
    "Generated by Project Board scripts/install_from_source.py.",
    "Generated by Problem Board tools/install_problem_board.py.",
)
DEFAULT_RELEASE_RETENTION = 3
DEFAULT_IMPORT_SMOKE = (
    "project_board",
    "app_foundation",
    "service_foundation",
    "connection_hub",
    "connection_hub_cli",
    "kdcube_cli",
)


class ReleaseInstallError(RuntimeError):
    """A candidate release could not become a complete runnable release."""

    def __init__(
        self,
        code: str,
        message: str,
        *,
        details: Mapping[str, Any] | None = None,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.details = dict(details or {})


def default_release_root(home: str | Path | None = None) -> Path:
    selected_home = (
        Path(home).expanduser().resolve() if home is not None else Path.home().resolve()
    )
    return selected_home / ".kdcube" / "client-runtime" / "tools" / "problem-board"


def releases_path(root: str | Path) -> Path:
    return Path(root).expanduser().resolve() / RELEASES_DIR


def release_path(root: str | Path, release_id: str) -> Path:
    identity = _release_id(release_id)
    return releases_path(root) / identity


def active_release_link(root: str | Path) -> Path:
    return releases_path(root) / CURRENT_LINK


def active_release_id(root: str | Path) -> str:
    link = active_release_link(root)
    if not link.is_symlink():
        return ""
    try:
        target = link.resolve(strict=True)
        relative = target.relative_to(releases_path(root))
    except (OSError, ValueError):
        return ""
    if len(relative.parts) != 1 or relative.name == CURRENT_LINK:
        return ""
    try:
        return _release_id(relative.name)
    except ReleaseInstallError:
        return ""


def active_release_path(root: str | Path) -> Path | None:
    identity = active_release_id(root)
    return release_path(root, identity) if identity else None


def active_python(root: str | Path) -> Path:
    return active_release_link(root) / VENV_DIR / "bin" / "python"


def active_pb(root: str | Path) -> Path:
    return active_release_link(root) / VENV_DIR / "bin" / "pb"


def read_installation(path: str | Path) -> dict[str, Any]:
    marker = Path(path) / INSTALLATION_MARKER
    try:
        value = json.loads(marker.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    if not isinstance(value, dict) or value.get("schema") != INSTALLATION_SCHEMA:
        return {}
    try:
        identity = _release_id(str(value.get("release_id") or ""))
    except ReleaseInstallError:
        return {}
    if Path(path).name != identity:
        return {}
    source = value.get("source")
    if not isinstance(source, dict) or source.get("mode") not in {
        "released",
        "snapshot",
    }:
        return {}
    environment = value.get("environment")
    if not isinstance(environment, dict):
        return {}
    return dict(value)


def installed_environment(path: str | Path) -> dict[str, Any]:
    release = Path(path)
    installation = read_installation(release)
    python = release / VENV_DIR / "bin" / "python"
    pb = release / VENV_DIR / "bin" / "pb"
    if not installation or not python.is_file() or not pb.is_file():
        return {}
    return installation


def published_release_id(version: str) -> str:
    clean = str(version or "").strip()
    if not clean:
        raise ReleaseInstallError(
            "work_client_release_version_invalid",
            "A published Project Board release needs an exact version.",
        )
    return hashlib.sha256(f"project-board:released:{clean}".encode("utf-8")).hexdigest()


def source_release_id(sources: Iterable[tuple[str, Path]]) -> str:
    """Hash clean source package trees without binding the identity to a path."""

    digest = hashlib.sha256()
    digest.update(b"project-board:source-release:v1\0")
    seen = False
    for label, raw_root in sources:
        root = Path(raw_root)
        clean_label = str(label or "").strip("/")
        if not clean_label or not root.is_dir():
            raise ReleaseInstallError(
                "work_client_release_source_missing",
                "A Project Board source release is missing a package directory.",
                details={"label": clean_label, "path": str(root)},
            )
        seen = True
        digest.update(clean_label.encode("utf-8"))
        digest.update(b"\0")
        for entry in sorted(root.rglob("*"), key=lambda value: value.as_posix()):
            relative = entry.relative_to(root).as_posix()
            if entry.is_symlink():
                raise ReleaseInstallError(
                    "work_client_release_source_link_refused",
                    "A Project Board source release cannot contain symbolic links.",
                    details={"path": f"{clean_label}/{relative}"},
                )
            if "__pycache__" in entry.relative_to(root).parts or entry.suffix in {
                ".pyc",
                ".pyo",
            }:
                continue
            if not entry.is_file():
                continue
            digest.update(relative.encode("utf-8"))
            digest.update(b"\0")
            with entry.open("rb") as handle:
                for chunk in iter(lambda: handle.read(1024 * 1024), b""):
                    digest.update(chunk)
            digest.update(b"\0")
    if not seen:
        raise ReleaseInstallError(
            "work_client_release_source_missing",
            "A Project Board source release needs at least one package directory.",
        )
    return digest.hexdigest()


def install_release_environment(
    *,
    root: str | Path,
    release_id: str,
    requirements: Sequence[str | Path],
    source: Mapping[str, Any],
    base_python: str | Path,
    smoke_imports: Sequence[str] = DEFAULT_IMPORT_SMOKE,
    expected_project_board_version: str = "",
) -> dict[str, Any]:
    """Create and smoke one candidate environment without activating it."""

    identity = _release_id(release_id)
    release = release_path(root, identity)
    requirement_values = tuple(str(value) for value in requirements if str(value))
    if not requirement_values:
        raise ReleaseInstallError(
            "work_client_release_requirements_missing",
            "A Project Board release needs at least one install requirement.",
        )
    source_value = dict(source)
    if source_value.get("mode") not in {"released", "snapshot"}:
        raise ReleaseInstallError(
            "work_client_release_source_invalid",
            "A Project Board release source must be released or snapshot.",
            details={"source": source_value},
        )

    existing = installed_environment(release)
    if existing:
        _smoke_environment(
            release,
            smoke_imports=smoke_imports,
            expected_project_board_version=expected_project_board_version,
        )
        return {**existing, "reused": True}

    if active_release_id(root) == identity:
        raise ReleaseInstallError(
            "work_client_release_active_environment_invalid",
            "The active Project Board release environment is incomplete; activate a different verified release before rebuilding it.",
            details={"release_id": identity, "path": str(release)},
        )

    release.mkdir(parents=True, exist_ok=True, mode=0o700)
    environment = release / VENV_DIR
    marker = release / INSTALLATION_MARKER
    shutil.rmtree(environment, ignore_errors=True)
    marker.unlink(missing_ok=True)
    try:
        _run((str(base_python), "-m", "venv", str(environment)))
        python = environment / "bin" / "python"
        _run(
            (
                str(python),
                "-m",
                "pip",
                "install",
                "--upgrade",
                *requirement_values,
            )
        )
        smoke = _smoke_environment(
            release,
            smoke_imports=smoke_imports,
            expected_project_board_version=expected_project_board_version,
        )
        record = {
            "schema": INSTALLATION_SCHEMA,
            "release_id": identity,
            "source": source_value,
            "installed_at": _utc_now(),
            "activated_at": "",
            "environment": {
                "path": str(environment),
                "python": str(python),
                "pb": str(environment / "bin" / "pb"),
                "project_board_version": smoke["project_board_version"],
                "imports": list(smoke_imports),
            },
            "launcher_version": LAUNCHER_VERSION,
        }
        _atomic_write_json(marker, record)
        return {**record, "reused": False}
    except BaseException:
        shutil.rmtree(environment, ignore_errors=True)
        marker.unlink(missing_ok=True)
        if not (release / "release.json").is_file():
            try:
                release.rmdir()
            except OSError:
                pass
        raise


def activate_installed_release(root: str | Path, release_id: str) -> str:
    """Atomically point ``releases/current`` at one complete environment."""

    selected_root = Path(root).expanduser().resolve()
    previous = active_release_id(selected_root)
    identity = str(release_id or "").strip()
    link = active_release_link(selected_root)
    link.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    if not identity:
        link.unlink(missing_ok=True)
        return previous
    identity = _release_id(identity)
    candidate = release_path(selected_root, identity)
    installation = installed_environment(candidate)
    if not installation:
        raise ReleaseInstallError(
            "work_client_release_environment_missing",
            "The Project Board release has no verified environment.",
            details={"release_id": identity, "path": str(candidate)},
        )
    installation["activated_at"] = _utc_now()
    _atomic_write_json(candidate / INSTALLATION_MARKER, installation)
    temporary = link.with_name(f".{CURRENT_LINK}.tmp-{os.getpid()}")
    temporary.unlink(missing_ok=True)
    os.symlink(identity, temporary)
    os.replace(temporary, link)
    return previous


def prune_installed_releases(
    root: str | Path,
    *,
    keep: Sequence[str] = (),
    retain: int = DEFAULT_RELEASE_RETENTION,
) -> list[str]:
    """Retain the active and most recently activated complete environments."""

    releases = releases_path(root)
    if not releases.is_dir():
        return []
    retained = {_release_id(value) for value in keep if str(value).strip()}
    active = active_release_id(root)
    if active:
        retained.add(active)
    complete: list[tuple[str, str]] = []
    for entry in releases.iterdir():
        if entry.is_symlink() or not entry.is_dir() or entry.name.startswith("."):
            continue
        installation = installed_environment(entry)
        if installation:
            complete.append(
                (
                    str(
                        installation.get("activated_at")
                        or installation.get("installed_at")
                        or ""
                    ),
                    entry.name,
                )
            )
    for _timestamp, identity in sorted(complete, reverse=True):
        if len(retained) >= max(1, int(retain)):
            break
        retained.add(identity)
    removed: list[str] = []
    for entry in sorted(releases.iterdir()):
        if entry.is_symlink() or not entry.is_dir() or entry.name in retained:
            continue
        shutil.rmtree(entry, ignore_errors=True)
        removed.append(entry.name)
    return removed


def launcher_status(path: str | Path, *, expected_pb: str | Path) -> dict[str, Any]:
    launcher = Path(path).expanduser()
    try:
        text = launcher.read_text(encoding="utf-8")
    except OSError:
        return {
            "path": str(launcher),
            "installed": False,
            "version": 0,
            "expected_pb": str(expected_pb),
        }
    marker = "Project Board launcher version "
    version = 0
    for line in text.splitlines():
        if marker in line:
            try:
                version = int(line.partition(marker)[2].rstrip("."))
            except ValueError:
                version = 0
            break
    return {
        "path": str(launcher),
        "installed": True,
        "version": version,
        "expected_version": LAUNCHER_VERSION,
        "expected_pb": str(expected_pb),
        "current": version == LAUNCHER_VERSION and str(expected_pb) in text,
    }


def validate_launcher(
    path: str | Path,
    *,
    expected_pb: str | Path,
    force: bool = False,
) -> Path:
    launcher = Path(path).expanduser()
    if os.path.lexists(launcher) and not _launcher_is_owned(
        launcher, Path(expected_pb)
    ):
        if not force:
            raise ReleaseInstallError(
                "work_client_launcher_unowned",
                f"Refusing to replace unrelated command at {launcher}.",
                details={"launcher": str(launcher)},
            )
    return launcher


def install_launcher(
    path: str | Path,
    *,
    expected_pb: str | Path,
    force: bool = False,
) -> Path:
    """Install the inert host launcher after its target release is ready."""

    launcher = validate_launcher(path, expected_pb=expected_pb, force=force)
    launcher.parent.mkdir(parents=True, exist_ok=True)
    temporary = launcher.with_name(f".{launcher.name}.tmp.{os.getpid()}")
    temporary.write_text(_launcher_text(Path(expected_pb)), encoding="utf-8")
    temporary.chmod(0o755)
    os.replace(temporary, launcher)
    return launcher


def _smoke_environment(
    release: Path,
    *,
    smoke_imports: Sequence[str],
    expected_project_board_version: str,
) -> dict[str, str]:
    environment = release / VENV_DIR
    python = environment / "bin" / "python"
    pb = environment / "bin" / "pb"
    if not python.is_file() or not pb.is_file():
        raise ReleaseInstallError(
            "work_client_release_command_missing",
            "The installed project-board distribution did not create its Python and pb commands.",
            details={"environment": str(environment)},
        )
    version_result = _run((str(pb), "--version"), capture=True)
    import_names = tuple(str(name) for name in smoke_imports if str(name))
    probe = (
        "import importlib, importlib.metadata, json; "
        f"names={import_names!r}; "
        "[importlib.import_module(name) for name in names]; "
        "print(json.dumps({'project_board_version': "
        "importlib.metadata.version('project-board'), 'imports': names}))"
    )
    import_result = _run((str(python), "-c", probe), capture=True)
    try:
        observed = json.loads(import_result.stdout)
    except json.JSONDecodeError as exc:
        raise ReleaseInstallError(
            "work_client_release_smoke_invalid",
            "The Project Board release import smoke did not return JSON.",
            details={"stdout": import_result.stdout[-1000:]},
        ) from exc
    version = str(observed.get("project_board_version") or "")
    if expected_project_board_version and version != expected_project_board_version:
        raise ReleaseInstallError(
            "work_client_release_version_unexpected",
            f"The candidate project-board version is {version}, not the approved {expected_project_board_version}.",
            details={
                "installed": version,
                "expected": expected_project_board_version,
            },
        )
    return {
        "pb_version": version_result.stdout.strip(),
        "project_board_version": version,
    }


def _launcher_text(pb_command: Path) -> str:
    return (
        "#!/bin/sh\n"
        f"# {LAUNCHER_MARKER}\n"
        f"# Project Board launcher version {LAUNCHER_VERSION}.\n"
        'PROBLEM_BOARD_INVOKED_PB="$0"\n'
        "export PROBLEM_BOARD_INVOKED_PB\n"
        f"exec {shlex.quote(str(pb_command))} \"$@\"\n"
    )


def _launcher_is_owned(launcher: Path, pb_command: Path) -> bool:
    if launcher.is_symlink():
        return launcher.resolve(strict=False) == pb_command
    if not launcher.is_file():
        return False
    current = launcher.read_text(encoding="utf-8", errors="replace")
    return LAUNCHER_MARKER in current or any(
        marker in current for marker in LEGACY_LAUNCHER_MARKERS
    )


def _run(
    command: Sequence[str], *, capture: bool = False
) -> subprocess.CompletedProcess[str]:
    environment = os.environ.copy()
    # A release smoke proves the candidate environment itself. Developer
    # shells and test runners commonly carry PYTHONPATH; inheriting it would
    # let a checkout satisfy imports that the candidate failed to install.
    environment.pop("PYTHONPATH", None)
    environment.pop("PYTHONHOME", None)
    try:
        return subprocess.run(
            tuple(command),
            check=True,
            capture_output=capture,
            text=True,
            env=environment,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        details: dict[str, Any] = {"command": list(command)}
        if isinstance(exc, subprocess.CalledProcessError):
            details.update(
                {
                    "returncode": exc.returncode,
                    "stdout": str(exc.stdout or "")[-2000:],
                    "stderr": str(exc.stderr or "")[-2000:],
                }
            )
        raise ReleaseInstallError(
            "work_client_release_install_failed",
            "The candidate Project Board release could not be installed and verified.",
            details=details,
        ) from exc


def _release_id(value: str) -> str:
    clean = str(value or "").strip().lower()
    if len(clean) != 64 or any(character not in "0123456789abcdef" for character in clean):
        raise ReleaseInstallError(
            "work_client_release_id_invalid",
            "A Project Board release id must be 64 lowercase hexadecimal characters.",
            details={"release_id": clean},
        )
    return clean


def _atomic_write_json(path: Path, value: Mapping[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    temporary = path.with_name(f".{path.name}.tmp-{os.getpid()}")
    with temporary.open("w", encoding="utf-8") as handle:
        json.dump(dict(value), handle, indent=2, sort_keys=True)
        handle.write("\n")
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(temporary, path)


def _utc_now() -> str:
    from datetime import datetime, timezone

    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


__all__ = [
    "CURRENT_LINK",
    "DEFAULT_IMPORT_SMOKE",
    "DEFAULT_RELEASE_RETENTION",
    "INSTALLATION_MARKER",
    "INSTALLATION_SCHEMA",
    "LAUNCHER_MARKER",
    "LAUNCHER_VERSION",
    "RELEASES_DIR",
    "ReleaseInstallError",
    "activate_installed_release",
    "active_pb",
    "active_python",
    "active_release_id",
    "active_release_link",
    "active_release_path",
    "default_release_root",
    "install_release_environment",
    "install_launcher",
    "installed_environment",
    "launcher_status",
    "prune_installed_releases",
    "published_release_id",
    "read_installation",
    "release_path",
    "releases_path",
    "source_release_id",
    "validate_launcher",
]
