#!/usr/bin/env python3
"""Install the Project Board host client from one clean App Ecosystem export."""

from __future__ import annotations

import argparse
import json
import os
import shlex
import subprocess
import sys
from pathlib import Path
from typing import Sequence


PACKAGE_PATHS = (
    Path("packages/app-foundation"),
    Path("packages/service-foundation"),
    Path("products/connection-hub/packages/connection-hub"),
    Path("products/connection-hub/packages/connection-hub-cli"),
    Path("products/project-board/packages/project-board"),
)
LAUNCHER_MARKER = "Generated by Project Board scripts/install_from_source.py."
LEGACY_LAUNCHER_MARKER = "Generated by Problem Board tools/install_problem_board.py."


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Install all first-party Project Board client distributions from "
            "one clean App Ecosystem source export."
        )
    )
    parser.add_argument("--source-root", required=True)
    parser.add_argument(
        "--venv",
        default=str(
            Path.home()
            / ".kdcube"
            / "client-runtime"
            / "tools"
            / "problem-board-venv"
        ),
    )
    parser.add_argument(
        "--command-dir",
        default=str(Path.home() / ".local" / "bin"),
    )
    parser.add_argument("--python", default=sys.executable)
    parser.add_argument("--force-launcher", action="store_true")
    return parser


def _run(command: Sequence[str]) -> None:
    subprocess.run(tuple(command), check=True)


def _run_json(command: Sequence[str]) -> dict[str, object]:
    completed = subprocess.run(
        tuple(command),
        check=True,
        capture_output=True,
        text=True,
    )
    try:
        value = json.loads(completed.stdout)
    except json.JSONDecodeError as exc:
        raise SystemExit(
            "Installed Project Board source verification did not return JSON."
        ) from exc
    if not isinstance(value, dict):
        raise SystemExit(
            "Installed Project Board source verification is not an object."
        )
    return value


def _first_party_packages(source_root: Path) -> tuple[Path, ...]:
    packages = tuple(source_root / relative for relative in PACKAGE_PATHS)
    missing = [str(path) for path in packages if not path.is_dir()]
    if missing:
        raise SystemExit(
            "The App Ecosystem source export is missing required package directories: "
            + ", ".join(missing)
        )
    return packages


def _launcher_text(pb_command: Path) -> str:
    return (
        "#!/bin/sh\n"
        f"# {LAUNCHER_MARKER}\n"
        f"exec {shlex.quote(str(pb_command))} \"$@\"\n"
    )


def _launcher_is_owned(launcher: Path, pb_command: Path) -> bool:
    if launcher.is_symlink():
        return launcher.resolve(strict=False) == pb_command
    if not launcher.is_file():
        return False
    current = launcher.read_text(encoding="utf-8", errors="replace")
    return LAUNCHER_MARKER in current or LEGACY_LAUNCHER_MARKER in current


def _install_launcher(
    *,
    command_dir: Path,
    pb_command: Path,
    force: bool,
) -> Path:
    command_dir.mkdir(parents=True, exist_ok=True)
    launcher = command_dir / "pb"
    if os.path.lexists(launcher) and not _launcher_is_owned(launcher, pb_command):
        if not force:
            raise SystemExit(
                f"Refusing to replace unrelated command at {launcher}; "
                "use --force-launcher after reviewing it."
            )
    temporary = launcher.with_name(f".{launcher.name}.tmp.{os.getpid()}")
    temporary.write_text(_launcher_text(pb_command), encoding="utf-8")
    temporary.chmod(0o755)
    os.replace(temporary, launcher)
    return launcher


def _installed_release_source(python: Path) -> dict[str, object]:
    return _run_json(
        (
            str(python),
            "-c",
            (
                "import json; "
                "from project_board.client.relay_source "
                "import installed_release_source; "
                "print(json.dumps(installed_release_source(), sort_keys=True))"
            ),
        )
    )


def install(
    *,
    source_root: Path,
    venv: Path,
    command_dir: Path,
    base_python: Path,
    force_launcher: bool,
) -> dict[str, object]:
    packages = _first_party_packages(source_root)
    python = venv / "bin" / "python"
    if not python.is_file():
        _run((str(base_python), "-m", "venv", str(venv)))

    # One resolver invocation binds every first-party dependency to this export.
    _run(
        (
            str(python),
            "-m",
            "pip",
            "install",
            "--upgrade",
            *(str(path) for path in packages),
        )
    )
    pb_command = venv / "bin" / "pb"
    if not pb_command.is_file():
        raise SystemExit(
            "The installed project-board distribution did not create "
            f"{pb_command}."
        )

    source = _installed_release_source(python)
    if source.get("mode") != "released":
        raise SystemExit(
            "The installed bootstrap is not isolated from a Git checkout: "
            + json.dumps(source, sort_keys=True)
        )
    launcher = _install_launcher(
        command_dir=command_dir,
        pb_command=pb_command,
        force=force_launcher,
    )
    return {
        "command": str(launcher),
        "venv": str(venv),
        "first_party_packages": [str(path) for path in packages],
        "installed_source": source,
        "ready": True,
    }


def main() -> int:
    args = _parser().parse_args()
    result = install(
        source_root=Path(args.source_root).expanduser().resolve(),
        venv=Path(args.venv).expanduser().resolve(),
        command_dir=Path(args.command_dir).expanduser().resolve(),
        base_python=Path(args.python).expanduser().resolve(),
        force_launcher=bool(args.force_launcher),
    )
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
