from __future__ import annotations

import importlib.util
import subprocess
from pathlib import Path

import pytest


PACKAGE_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = PACKAGE_ROOT / "scripts" / "install_from_source.py"


def _installer_module():
    spec = importlib.util.spec_from_file_location(
        "project_board_source_installer", SCRIPT
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _source_exports(module, root: Path) -> tuple[Path, Path, tuple[Path, ...]]:
    source_root = root / "app-ecosystem"
    kdcube_source_root = root / "kdcube"
    roots = {
        module.APP_ECOSYSTEM_COMPONENT: source_root,
        module.KDCUBE_COMPONENT: kdcube_source_root,
    }
    paths = tuple(
        roots[component] / relative
        for component in (
            module.APP_ECOSYSTEM_COMPONENT,
            module.KDCUBE_COMPONENT,
        )
        for relative in module.SOURCE_PATHS_BY_COMPONENT[component]
    )
    for path in paths:
        path.mkdir(parents=True)
    return source_root, kdcube_source_root, paths


def test_source_installer_names_the_complete_first_party_package_family(tmp_path: Path):
    installer = _installer_module()
    source_root, kdcube_source_root, expected = _source_exports(
        installer, tmp_path
    )

    assert installer._first_party_packages(
        source_root, kdcube_source_root
    ) == expected
    assert [path.name for path in expected] == [
        "project-board",
        "app-foundation",
        "service-foundation",
        "connection-hub",
        "connection-hub-cli",
        "kdcube_cli",
    ]


def test_source_installer_resolves_all_first_party_packages_in_one_pip_call(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    installer = _installer_module()
    source_root, kdcube_source_root, packages = _source_exports(
        installer, tmp_path / "source"
    )
    release_root = tmp_path / "releases-root"
    release_id = "a" * 64
    environment = release_root / "releases" / release_id / "venv"
    calls: list[dict[str, object]] = []
    lock_events: list[tuple[str, Path]] = []

    class _Lock:
        def __init__(self, root: Path) -> None:
            self.root = root

        def __enter__(self):
            lock_events.append(("enter", self.root))

        def __exit__(self, exc_type, exc, traceback):
            del exc_type, exc, traceback
            lock_events.append(("exit", self.root))

    def install_release_environment(**kwargs):
        calls.append(kwargs)
        return {
            "environment": {
                "path": str(environment),
                "python": str(environment / "bin" / "python"),
                "pb": str(environment / "bin" / "pb"),
            }
        }

    monkeypatch.setattr(installer._RELEASE_INSTALL, "source_release_id", lambda _: release_id)
    monkeypatch.setattr(
        installer._RELEASE_INSTALL,
        "install_release_environment",
        install_release_environment,
    )
    monkeypatch.setattr(
        installer._RELEASE_INSTALL,
        "activate_installed_release",
        lambda root, identity: "",
    )
    monkeypatch.setattr(
        installer._RELEASE_INSTALL,
        "prune_installed_releases",
        lambda root, keep: [],
    )
    monkeypatch.setattr(
        installer._RELEASE_INSTALL,
        "activation_lock",
        lambda root: _Lock(root),
    )

    result = installer.install(
        source_root=source_root,
        kdcube_source_root=kdcube_source_root,
        release_root=release_root,
        command_dir=tmp_path / "bin",
        base_python=Path("/usr/bin/python3"),
        force_launcher=False,
    )

    assert len(calls) == 1
    assert calls[0]["requirements"] == packages
    assert calls[0]["base_python"] == Path("/usr/bin/python3")
    assert calls[0]["smoke_imports"] == (
        *installer.CLIENT_SOURCE_IMPORTS,
        *installer._RELEASE_INSTALL.DEFAULT_IMPORT_SMOKE,
    )
    assert lock_events == [
        ("enter", release_root),
        ("exit", release_root),
    ]
    assert result["release_id"] == release_id
    assert result["installed_source"]["mode"] == "snapshot"
    assert Path(str(result["command"])).read_text(encoding="utf-8").startswith(
        "#!/bin/sh\n# Generated by Project Board"
    )
    assert str(release_root / "releases" / "current" / "venv" / "bin" / "pb") in Path(
        str(result["command"])
    ).read_text(encoding="utf-8")


def test_source_installer_replaces_only_an_owned_launcher_by_default(tmp_path: Path):
    installer = _installer_module()
    command_dir = tmp_path / "bin"
    command_dir.mkdir()
    launcher = command_dir / "pb"
    pb_command = tmp_path / "venv" / "bin" / "pb"
    pb_command.parent.mkdir(parents=True)
    pb_command.write_text("", encoding="utf-8")

    launcher.write_text("#!/bin/sh\necho unrelated\n", encoding="utf-8")
    with pytest.raises(SystemExit, match="Refusing to replace unrelated command"):
        installer._install_launcher(
            command_dir=command_dir,
            pb_command=pb_command,
            force=False,
        )

    launcher.write_text(
        "#!/bin/sh\n# Generated by Problem Board tools/install_problem_board.py.\n",
        encoding="utf-8",
    )
    installer._install_launcher(
        command_dir=command_dir,
        pb_command=pb_command,
        force=False,
    )
    assert str(pb_command) in launcher.read_text(encoding="utf-8")
    assert 'PROBLEM_BOARD_INVOKED_PB="$0"' in launcher.read_text(encoding="utf-8")


def test_source_installer_restores_an_absent_launcher_when_activation_fails(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    installer = _installer_module()
    source_root, kdcube_source_root, _packages = _source_exports(
        installer, tmp_path / "source"
    )
    release_root = tmp_path / "release-root"
    command_dir = tmp_path / "bin"
    release_id = "c" * 64
    activations: list[str] = []

    monkeypatch.setattr(
        installer._RELEASE_INSTALL,
        "source_release_id",
        lambda _sources: release_id,
    )
    monkeypatch.setattr(
        installer._RELEASE_INSTALL,
        "install_release_environment",
        lambda **_kwargs: {
            "environment": {
                "python": str(release_root / "candidate" / "python"),
                "pb": str(release_root / "candidate" / "pb"),
            }
        },
    )

    def activate(_root: Path, identity: str) -> str:
        activations.append(identity)
        return "" if identity else release_id

    def fail_launcher(*, command_dir: Path, pb_command: Path, force: bool) -> Path:
        del pb_command, force
        launcher = command_dir / "pb"
        launcher.parent.mkdir(parents=True, exist_ok=True)
        launcher.write_text("candidate launcher\n", encoding="utf-8")
        raise RuntimeError("launcher write failed")

    monkeypatch.setattr(
        installer._RELEASE_INSTALL,
        "activate_installed_release",
        activate,
    )
    monkeypatch.setattr(installer, "_install_launcher", fail_launcher)

    with pytest.raises(RuntimeError, match="launcher write failed"):
        installer.install(
            source_root=source_root,
            kdcube_source_root=kdcube_source_root,
            release_root=release_root,
            command_dir=command_dir,
            base_python=Path("/usr/bin/python3"),
            force_launcher=False,
        )

    assert activations == [release_id, ""]
    assert not (command_dir / "pb").exists()


def test_the_inert_launcher_executes_current_and_records_its_own_path(
    tmp_path: Path,
) -> None:
    installer = _installer_module()
    root = tmp_path / "client"
    identity = "a" * 64
    command = root / "releases" / identity / "venv" / "bin" / "pb"
    command.parent.mkdir(parents=True)
    command.write_text(
        "#!/bin/sh\nprintf '%s\\n' \"$PROBLEM_BOARD_INVOKED_PB\"\n",
        encoding="utf-8",
    )
    command.chmod(0o755)
    current = root / "releases" / "current"
    current.symlink_to(identity)
    launcher = installer._install_launcher(
        command_dir=tmp_path / "bin",
        pb_command=current / "venv" / "bin" / "pb",
        force=False,
    )

    result = subprocess.run(
        (str(launcher),),
        check=True,
        capture_output=True,
        text=True,
    )

    assert result.stdout.strip() == str(launcher)


def test_switching_current_delivers_new_loader_behavior_without_reinstalling_launcher(
    tmp_path: Path,
) -> None:
    installer = _installer_module()
    release_install = installer._RELEASE_INSTALL
    root = tmp_path / "client"

    for identity, output in (("a" * 64, "old loader"), ("b" * 64, "new loader")):
        release = release_install.release_path(root, identity)
        commands = release / "venv" / "bin"
        commands.mkdir(parents=True)
        python = commands / "python"
        python.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
        python.chmod(0o755)
        pb = commands / "pb"
        pb.write_text(f"#!/bin/sh\nprintf '%s\\n' '{output}'\n", encoding="utf-8")
        pb.chmod(0o755)
        release_install._atomic_write_json(
            release / release_install.INSTALLATION_MARKER,
            {
                "schema": release_install.INSTALLATION_SCHEMA,
                "release_id": identity,
                "source": {"mode": "released", "version": output},
                "installed_at": "2026-09-25T00:00:00Z",
                "activated_at": "",
                "environment": {
                    "path": str(release / "venv"),
                    "python": str(python),
                    "pb": str(pb),
                },
                "launcher_version": release_install.LAUNCHER_VERSION,
            },
        )

    release_install.activate_installed_release(root, "a" * 64)
    launcher = installer._install_launcher(
        command_dir=tmp_path / "bin",
        pb_command=release_install.active_pb(root),
        force=False,
    )
    launcher_before = launcher.read_bytes()
    first = subprocess.run((str(launcher),), check=True, capture_output=True, text=True)

    release_install.activate_installed_release(root, "b" * 64)
    second = subprocess.run((str(launcher),), check=True, capture_output=True, text=True)

    assert first.stdout.strip() == "old loader"
    assert second.stdout.strip() == "new loader"
    assert launcher.read_bytes() == launcher_before


def test_source_installer_finds_a_running_current_path_launchd_relay(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    installer = _installer_module()
    root = tmp_path / "client"
    identity = "a" * 64
    release = installer._RELEASE_INSTALL.release_path(root, identity)
    release.mkdir(parents=True)
    installer._RELEASE_INSTALL.active_release_link(root).symlink_to(identity)
    service_id = "tech.kdcube.problem-board.relay.123456789abc"
    definition = (
        tmp_path
        / "home"
        / "Library"
        / "LaunchAgents"
        / f"{service_id}.plist"
    )
    definition.parent.mkdir(parents=True)
    definition.write_bytes(
        installer.plistlib.dumps(
            {
                "Label": service_id,
                "ProgramArguments": [
                    str(installer._RELEASE_INSTALL.active_python(root)),
                    "-m",
                    "project_board.client.entrypoint",
                    "relay",
                    "--config",
                    str(tmp_path / "relay.json"),
                ],
            }
        )
    )
    commands: list[tuple[str, ...]] = []

    def run(command, **_kwargs):
        commands.append(tuple(command))
        return subprocess.CompletedProcess(command, 0, "running", "")

    monkeypatch.setattr(installer.subprocess, "run", run)

    running = installer._running_current_relays(
        root,
        user_home=tmp_path / "home",
        system="Darwin",
    )

    assert running == [
        {"service_id": service_id, "definition": str(definition)}
    ]
    assert commands == [
        ("launchctl", "print", f"gui/{installer.os.getuid()}/{service_id}")
    ]


def test_source_installer_finds_a_running_current_path_systemd_relay(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    installer = _installer_module()
    root = tmp_path / "client"
    identity = "c" * 64
    release = installer._RELEASE_INSTALL.release_path(root, identity)
    release.mkdir(parents=True)
    installer._RELEASE_INSTALL.active_release_link(root).symlink_to(identity)
    service_id = "kdcube-problem-board-relay-123456789abc.service"
    definition = (
        tmp_path / "home" / ".config" / "systemd" / "user" / service_id
    )
    definition.parent.mkdir(parents=True)
    definition.write_text(
        "[Service]\n"
        f'ExecStart="{installer._RELEASE_INSTALL.active_python(root)}" '
        '"-m" "project_board.client.entrypoint" "relay" '
        f'"--config" "{tmp_path / "relay.json"}"\n',
        encoding="utf-8",
    )
    commands: list[tuple[str, ...]] = []

    def run(command, **_kwargs):
        commands.append(tuple(command))
        return subprocess.CompletedProcess(command, 0, "active", "")

    monkeypatch.setattr(installer.subprocess, "run", run)

    running = installer._running_current_relays(
        root,
        user_home=tmp_path / "home",
        system="Linux",
    )

    assert running == [
        {"service_id": service_id, "definition": str(definition)}
    ]
    assert commands == [
        ("systemctl", "--user", "is-active", service_id)
    ]


def test_source_installer_refuses_a_migrated_host_before_building(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    installer = _installer_module()
    root = tmp_path / "client"
    identity = "b" * 64
    release = installer._RELEASE_INSTALL.release_path(root, identity)
    release.mkdir(parents=True)
    installer._RELEASE_INSTALL.active_release_link(root).symlink_to(identity)
    monkeypatch.setattr(
        installer,
        "_running_current_relays",
        lambda _root: [
            {
                "service_id": "tech.kdcube.problem-board.relay.123456789abc",
                "definition": "/tmp/relay.plist",
            }
        ],
    )

    with pytest.raises(
        SystemExit,
        match="work_client_source_installer_migrated_host.*pb source use-code",
    ):
        installer.install(
            source_root=tmp_path / "missing-app-source",
            kdcube_source_root=tmp_path / "missing-kdcube-source",
            release_root=root,
            command_dir=tmp_path / "bin",
            base_python=Path("/usr/bin/python3"),
            force_launcher=False,
        )
