from __future__ import annotations

import importlib.util
import subprocess
from pathlib import Path

import pytest


PACKAGE_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = PACKAGE_ROOT / "scripts" / "install_from_source.py"


def _installer_module():
    spec = importlib.util.spec_from_file_location(
        "project_board_source_installer", SCRIPT
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _source_exports(module, root: Path) -> tuple[Path, Path, tuple[Path, ...]]:
    source_root = root / "app-ecosystem"
    kdcube_source_root = root / "kdcube"
    roots = {
        module.APP_ECOSYSTEM_COMPONENT: source_root,
        module.KDCUBE_COMPONENT: kdcube_source_root,
    }
    paths = tuple(
        roots[component] / relative
        for component in (
            module.APP_ECOSYSTEM_COMPONENT,
            module.KDCUBE_COMPONENT,
        )
        for relative in module.SOURCE_PATHS_BY_COMPONENT[component]
    )
    for path in paths:
        path.mkdir(parents=True)
    return source_root, kdcube_source_root, paths


def test_source_installer_names_the_complete_first_party_package_family(tmp_path: Path):
    installer = _installer_module()
    source_root, kdcube_source_root, expected = _source_exports(
        installer, tmp_path
    )

    assert installer._first_party_packages(
        source_root, kdcube_source_root
    ) == expected
    assert [path.name for path in expected] == [
        "project-board",
        "app-foundation",
        "service-foundation",
        "connection-hub",
        "connection-hub-cli",
        "kdcube_cli",
    ]


def test_source_installer_resolves_all_first_party_packages_in_one_pip_call(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    installer = _installer_module()
    source_root, kdcube_source_root, packages = _source_exports(
        installer, tmp_path / "source"
    )
    release_root = tmp_path / "releases-root"
    release_id = "a" * 64
    environment = release_root / "releases" / release_id / "venv"
    calls: list[dict[str, object]] = []

    def install_release_environment(**kwargs):
        calls.append(kwargs)
        return {
            "environment": {
                "path": str(environment),
                "python": str(environment / "bin" / "python"),
                "pb": str(environment / "bin" / "pb"),
            }
        }

    monkeypatch.setattr(installer._RELEASE_INSTALL, "source_release_id", lambda _: release_id)
    monkeypatch.setattr(
        installer._RELEASE_INSTALL,
        "install_release_environment",
        install_release_environment,
    )
    monkeypatch.setattr(
        installer._RELEASE_INSTALL,
        "activate_installed_release",
        lambda root, identity: "",
    )
    monkeypatch.setattr(
        installer._RELEASE_INSTALL,
        "prune_installed_releases",
        lambda root, keep: [],
    )

    result = installer.install(
        source_root=source_root,
        kdcube_source_root=kdcube_source_root,
        release_root=release_root,
        command_dir=tmp_path / "bin",
        base_python=Path("/usr/bin/python3"),
        force_launcher=False,
    )

    assert len(calls) == 1
    assert calls[0]["requirements"] == packages
    assert calls[0]["base_python"] == Path("/usr/bin/python3")
    assert calls[0]["smoke_imports"] == installer.CLIENT_SOURCE_IMPORTS
    assert result["release_id"] == release_id
    assert result["installed_source"]["mode"] == "snapshot"
    assert Path(str(result["command"])).read_text(encoding="utf-8").startswith(
        "#!/bin/sh\n# Generated by Project Board"
    )
    assert str(release_root / "releases" / "current" / "venv" / "bin" / "pb") in Path(
        str(result["command"])
    ).read_text(encoding="utf-8")


def test_source_installer_replaces_only_an_owned_launcher_by_default(tmp_path: Path):
    installer = _installer_module()
    command_dir = tmp_path / "bin"
    command_dir.mkdir()
    launcher = command_dir / "pb"
    pb_command = tmp_path / "venv" / "bin" / "pb"
    pb_command.parent.mkdir(parents=True)
    pb_command.write_text("", encoding="utf-8")

    launcher.write_text("#!/bin/sh\necho unrelated\n", encoding="utf-8")
    with pytest.raises(SystemExit, match="Refusing to replace unrelated command"):
        installer._install_launcher(
            command_dir=command_dir,
            pb_command=pb_command,
            force=False,
        )

    launcher.write_text(
        "#!/bin/sh\n# Generated by Problem Board tools/install_problem_board.py.\n",
        encoding="utf-8",
    )
    installer._install_launcher(
        command_dir=command_dir,
        pb_command=pb_command,
        force=False,
    )
    assert str(pb_command) in launcher.read_text(encoding="utf-8")
    assert 'PROBLEM_BOARD_INVOKED_PB="$0"' in launcher.read_text(encoding="utf-8")


def test_the_inert_launcher_executes_current_and_records_its_own_path(
    tmp_path: Path,
) -> None:
    installer = _installer_module()
    root = tmp_path / "client"
    identity = "a" * 64
    command = root / "releases" / identity / "venv" / "bin" / "pb"
    command.parent.mkdir(parents=True)
    command.write_text(
        "#!/bin/sh\nprintf '%s\\n' \"$PROBLEM_BOARD_INVOKED_PB\"\n",
        encoding="utf-8",
    )
    command.chmod(0o755)
    current = root / "releases" / "current"
    current.symlink_to(identity)
    launcher = installer._install_launcher(
        command_dir=tmp_path / "bin",
        pb_command=current / "venv" / "bin" / "pb",
        force=False,
    )

    result = subprocess.run(
        (str(launcher),),
        check=True,
        capture_output=True,
        text=True,
    )

    assert result.stdout.strip() == str(launcher)


def test_switching_current_delivers_new_loader_behavior_without_reinstalling_launcher(
    tmp_path: Path,
) -> None:
    installer = _installer_module()
    release_install = installer._RELEASE_INSTALL
    root = tmp_path / "client"

    for identity, output in (("a" * 64, "old loader"), ("b" * 64, "new loader")):
        release = release_install.release_path(root, identity)
        commands = release / "venv" / "bin"
        commands.mkdir(parents=True)
        python = commands / "python"
        python.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
        python.chmod(0o755)
        pb = commands / "pb"
        pb.write_text(f"#!/bin/sh\nprintf '%s\\n' '{output}'\n", encoding="utf-8")
        pb.chmod(0o755)
        release_install._atomic_write_json(
            release / release_install.INSTALLATION_MARKER,
            {
                "schema": release_install.INSTALLATION_SCHEMA,
                "release_id": identity,
                "source": {"mode": "released", "version": output},
                "installed_at": "2026-09-25T00:00:00Z",
                "activated_at": "",
                "environment": {
                    "path": str(release / "venv"),
                    "python": str(python),
                    "pb": str(pb),
                },
                "launcher_version": release_install.LAUNCHER_VERSION,
            },
        )

    release_install.activate_installed_release(root, "a" * 64)
    launcher = installer._install_launcher(
        command_dir=tmp_path / "bin",
        pb_command=release_install.active_pb(root),
        force=False,
    )
    launcher_before = launcher.read_bytes()
    first = subprocess.run((str(launcher),), check=True, capture_output=True, text=True)

    release_install.activate_installed_release(root, "b" * 64)
    second = subprocess.run((str(launcher),), check=True, capture_output=True, text=True)

    assert first.stdout.strip() == "old loader"
    assert second.stdout.strip() == "new loader"
    assert launcher.read_bytes() == launcher_before
