from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest


PACKAGE_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = PACKAGE_ROOT / "scripts" / "install_from_source.py"


def _installer_module():
    spec = importlib.util.spec_from_file_location(
        "project_board_source_installer", SCRIPT
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _source_exports(module, root: Path) -> tuple[Path, Path, tuple[Path, ...]]:
    source_root = root / "app-ecosystem"
    kdcube_source_root = root / "kdcube"
    roots = {
        module.APP_ECOSYSTEM_COMPONENT: source_root,
        module.KDCUBE_COMPONENT: kdcube_source_root,
    }
    paths = tuple(
        roots[component] / relative
        for component in (
            module.APP_ECOSYSTEM_COMPONENT,
            module.KDCUBE_COMPONENT,
        )
        for relative in module.SOURCE_PATHS_BY_COMPONENT[component]
    )
    for path in paths:
        path.mkdir(parents=True)
    return source_root, kdcube_source_root, paths


def test_source_installer_names_the_complete_first_party_package_family(tmp_path: Path):
    installer = _installer_module()
    source_root, kdcube_source_root, expected = _source_exports(
        installer, tmp_path
    )

    assert installer._first_party_packages(
        source_root, kdcube_source_root
    ) == expected
    assert [path.name for path in expected] == [
        "project-board",
        "app-foundation",
        "service-foundation",
        "connection-hub",
        "connection-hub-cli",
        "kdcube_cli",
    ]


def test_source_installer_resolves_all_first_party_packages_in_one_pip_call(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    installer = _installer_module()
    source_root, kdcube_source_root, packages = _source_exports(
        installer, tmp_path / "source"
    )
    venv = tmp_path / "venv"
    python = venv / "bin" / "python"
    pb_command = venv / "bin" / "pb"
    python.parent.mkdir(parents=True)
    python.write_text("", encoding="utf-8")
    pb_command.write_text("", encoding="utf-8")
    commands: list[tuple[str, ...]] = []

    monkeypatch.setattr(
        installer,
        "_run",
        lambda command: commands.append(tuple(command)),
    )
    monkeypatch.setattr(
        installer,
        "_installed_release_source",
        lambda _python: {"mode": "released", "version": "2026.09.23.0158"},
    )

    result = installer.install(
        source_root=source_root,
        kdcube_source_root=kdcube_source_root,
        venv=venv,
        command_dir=tmp_path / "bin",
        base_python=Path("/usr/bin/python3"),
        force_launcher=False,
    )

    assert commands == [
        (
            str(python),
            "-m",
            "pip",
            "install",
            "--upgrade",
            *(str(path) for path in packages),
        )
    ]
    assert result["installed_source"] == {
        "mode": "released",
        "version": "2026.09.23.0158",
    }
    assert Path(str(result["command"])).read_text(encoding="utf-8").startswith(
        "#!/bin/sh\n# Generated by Project Board"
    )


def test_source_installer_replaces_only_an_owned_launcher_by_default(tmp_path: Path):
    installer = _installer_module()
    command_dir = tmp_path / "bin"
    command_dir.mkdir()
    launcher = command_dir / "pb"
    pb_command = tmp_path / "venv" / "bin" / "pb"
    pb_command.parent.mkdir(parents=True)
    pb_command.write_text("", encoding="utf-8")

    launcher.write_text("#!/bin/sh\necho unrelated\n", encoding="utf-8")
    with pytest.raises(SystemExit, match="Refusing to replace unrelated command"):
        installer._install_launcher(
            command_dir=command_dir,
            pb_command=pb_command,
            force=False,
        )

    launcher.write_text(
        "#!/bin/sh\n# Generated by Problem Board tools/install_problem_board.py.\n",
        encoding="utf-8",
    )
    installer._install_launcher(
        command_dir=command_dir,
        pb_command=pb_command,
        force=False,
    )
    assert str(pb_command) in launcher.read_text(encoding="utf-8")
